# Generated by Django 3.2.6 on 2022-04-14 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methodologies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.URLField(default='/', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
