# Generated by Django 3.2.6 on 2022-04-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methodologies', '0002_auto_20220414_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_added',
            field=models.DateTimeField(),
        ),
    ]
